<?php  //[STAMP] 0685ff03391bb4534b8fabcdb0f42975
// phpcs:ignoreFile
namespace SprykerTest\Zed\AppPayment\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build

trait PaymentPersistenceTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();


}
